#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "fastokens",
#     "huggingface-hub>=0.24",
#     "datasets>=3.0",
# ]
# ///
"""Batch-encode + decode benchmark for fastokens.

Builds on top of the single-prompt run by reusing the existing
``inputs.jsonl`` + ``texts/`` corpus and adding:

- Synthetic 1K and 4K single-prompt samples (truncated from real LongBench
  contexts so every bucket is populated).
- Batch encode timings at sizes {8, 32, 128} × token lengths {1K, 4K}.
- Single decode timings across all five buckets {1K, 4K, 16K, 64K, 100K}.
- Batch decode timings matching the batch encode workloads.

Outputs to ``bench/results/longbench/``:
- ``inputs_batch.jsonl`` — manifest of all batch+decode workloads (kind,
  model, sha1 references, target_tokens, batch_size).
- ``fastokens_batch.json`` — per-(model, kind, params) timings.
"""

from __future__ import annotations

import hashlib
import json
import os
import statistics
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
RESULTS_DIR = REPO_ROOT / "bench" / "results" / "longbench"
TEXTS_DIR = RESULTS_DIR / "texts"
EXISTING_INPUTS = RESULTS_DIR / "inputs.jsonl"
INPUTS_BATCH_PATH = RESULTS_DIR / "inputs_batch.jsonl"
TIMINGS_PATH = RESULTS_DIR / "fastokens_batch.json"

SINGLE_BUCKETS = [1024, 4096, 16384, 65536, 100_000]
SYNTHETIC_BUCKETS = [1024, 4096]   # generated by truncating an existing context
BATCH_BUCKETS = [1024, 4096]        # batched workloads at these lengths only
BATCH_SIZES = [8, 32, 128]
SAMPLES_PER_SINGLE_BUCKET = 3
WARMUP = 3
ITERS = 10

MODEL_FILTER = os.environ.get("MODEL_FILTER")


def log(msg: str) -> None:
    print(msg, file=sys.stderr, flush=True)


def sha1_of(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8")).hexdigest()


def write_text(text: str) -> str:
    digest = sha1_of(text)
    path = TEXTS_DIR / f"{digest}.txt"
    if not path.exists():
        path.write_text(text, encoding="utf-8")
    return digest


def read_text(sha: str) -> str:
    return (TEXTS_DIR / f"{sha}.txt").read_text(encoding="utf-8")


def _id_count(ids) -> int:
    if isinstance(ids, list):
        return len(ids)
    if hasattr(ids, "ids"):
        return len(ids.ids)
    if hasattr(ids, "input_ids"):
        return len(ids.input_ids)
    return len(list(ids))


def _to_id_list(ids):
    if isinstance(ids, list):
        return ids
    if hasattr(ids, "ids"):
        return list(ids.ids)
    if hasattr(ids, "input_ids"):
        return list(ids.input_ids)
    return list(ids)


def _p95(samples: list[float]) -> float:
    if not samples:
        return 0.0
    s = sorted(samples)
    k = max(0, int(round(0.95 * (len(s) - 1))))
    return s[k]


def time_one(fn) -> dict:
    """Time ``fn`` with WARMUP warmups + ITERS timed iterations (in ms)."""
    for _ in range(WARMUP):
        fn()
    samples_ms: list[float] = []
    for _ in range(ITERS):
        t0 = time.perf_counter_ns()
        fn()
        samples_ms.append((time.perf_counter_ns() - t0) / 1_000_000)
    return {
        "samples_ms": samples_ms,
        "median_ms": statistics.median(samples_ms),
        "p95_ms": _p95(samples_ms),
    }


# ---------------------------------------------------------------------------
# Load existing single-prompt manifest
# ---------------------------------------------------------------------------


def load_existing_inputs() -> dict[str, dict[int, list[dict]]]:
    """Returns ``{model: {bucket: [row, ...]}}`` from the prior run's inputs.jsonl."""
    if not EXISTING_INPUTS.exists():
        sys.exit(f"missing {EXISTING_INPUTS} — run run_fastokens.py first.")
    by_model: dict[str, dict[int, list[dict]]] = {}
    with EXISTING_INPUTS.open() as fh:
        for line in fh:
            row = json.loads(line)
            by_model.setdefault(row["model"], {}).setdefault(row["bucket"], []).append(row)
    return by_model


# ---------------------------------------------------------------------------
# Synthetic truncation for 1K / 4K
# ---------------------------------------------------------------------------


def synthesize_truncated_text(tok, source_text: str, target_tokens: int) -> tuple[str, int]:
    """Truncate ``source_text`` to ``target_tokens`` via encode→slice→decode.

    Re-encodes the decoded result to discover the actual token count (BPE
    decode→encode roundtrips are not exact). Returns ``(text, actual_tokens)``.
    """
    ids = _to_id_list(tok.encode(source_text))
    if len(ids) < target_tokens:
        return source_text, len(ids)
    truncated_ids = ids[:target_tokens]
    decoded = tok.decode(truncated_ids)
    if not isinstance(decoded, str):
        decoded = str(decoded)
    actual = _id_count(tok.encode(decoded))
    return decoded, actual


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    from fastokens._native import Tokenizer  # type: ignore

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    TEXTS_DIR.mkdir(parents=True, exist_ok=True)

    existing = load_existing_inputs()
    models = sorted(existing.keys())
    if MODEL_FILTER:
        wanted = {m.strip() for m in MODEL_FILTER.split(",") if m.strip()}
        models = [m for m in models if m in wanted]
    log(f"Batch+decode bench over {len(models)} models")

    manifest_rows: list[dict] = []
    timings: dict[str, dict] = {}

    for model in models:
        log(f"\n=== {model} ===")
        try:
            tok = Tokenizer.from_model(model)
        except Exception as exc:  # noqa: BLE001
            log(f"  load failed: {exc!r}")
            timings[model] = {"error": f"load failed: {exc!r}"}
            continue

        model_timings: dict[str, dict] = {
            "single_synth": {},   # {bucket: [sample, …]}
            "single_decode": {},  # {bucket: [sample, …]}  — covers all 5 buckets
            "batch_encode": {},   # {f"{bucket}|{batch_size}": …}
            "batch_decode": {},   # {f"{bucket}|{batch_size}": …}
        }

        # ---- 1. Synthetic 1K / 4K single samples (encode timings) -----------
        # Source: take the smallest-natural-token sample from the existing 16K
        # bucket (largest available short bucket) and truncate down. This keeps
        # the prompt content realistic.
        source_pool = []
        for b in (16384, 65536, 100_000):
            for row in existing[model].get(b, []):
                source_pool.append(row["sha1"])
            if source_pool:
                break

        if not source_pool:
            log("  no source contexts available for synthetic truncation; skipping synth.")
        else:
            synth_sha_per_bucket: dict[int, list[str]] = {}
            for bucket in SYNTHETIC_BUCKETS:
                samples_out = []
                synth_sha_per_bucket[bucket] = []
                for i in range(SAMPLES_PER_SINGLE_BUCKET):
                    sha_src = source_pool[i % len(source_pool)]
                    src_text = read_text(sha_src)
                    text, actual = synthesize_truncated_text(tok, src_text, bucket)
                    sha = write_text(text)
                    synth_sha_per_bucket[bucket].append(sha)
                    manifest_rows.append({
                        "kind": "single_synth",
                        "model": model,
                        "bucket": bucket,
                        "sample_idx": i,
                        "sha1": sha,
                        "source_sha1": sha_src,
                        "natural_tokens": actual,
                    })
                    text_for_timing = text
                    timing = time_one(lambda t=text_for_timing: tok.encode(t))
                    timing["tokens"] = actual
                    timing["sha1"] = sha
                    timing["sample_idx"] = i
                    samples_out.append(timing)
                    log(
                        f"  single_synth bucket={bucket} sample={i}: tokens={actual} "
                        f"median={timing['median_ms']:.3f}ms"
                    )
                model_timings["single_synth"][str(bucket)] = samples_out

        # ---- 2. Single decode timings across all 5 buckets ------------------
        # Use existing samples from the prior run for {16384, 65536, 100000} and
        # the freshly-synthesised samples for {1024, 4096}.
        for bucket in SINGLE_BUCKETS:
            samples_out = []
            if bucket in SYNTHETIC_BUCKETS:
                shas = synth_sha_per_bucket.get(bucket, []) if source_pool else []
            else:
                shas = [r["sha1"] for r in existing[model].get(bucket, [])]
            for i, sha in enumerate(shas):
                text = read_text(sha)
                ids = _to_id_list(tok.encode(text))
                timing = time_one(lambda ids=ids: tok.decode(ids))
                timing["tokens"] = len(ids)
                timing["sha1"] = sha
                timing["sample_idx"] = i
                samples_out.append(timing)
                manifest_rows.append({
                    "kind": "single_decode",
                    "model": model,
                    "bucket": bucket,
                    "sample_idx": i,
                    "sha1": sha,
                    "natural_tokens": len(ids),
                })
                log(
                    f"  single_decode bucket={bucket} sample={i}: tokens={len(ids)} "
                    f"median={timing['median_ms']:.3f}ms"
                )
            if samples_out:
                model_timings["single_decode"][str(bucket)] = samples_out

        # ---- 3. Batch encode + batch decode at 1K and 4K --------------------
        for bucket in BATCH_BUCKETS:
            shas = synth_sha_per_bucket.get(bucket, []) if source_pool else []
            if not shas:
                continue
            base_texts = [read_text(s) for s in shas]
            for batch_size in BATCH_SIZES:
                batch_texts = [base_texts[i % len(base_texts)] for i in range(batch_size)]
                batch_shas = [shas[i % len(shas)] for i in range(batch_size)]
                # encode_batch
                enc_timing = time_one(lambda b=batch_texts: tok.encode_batch(b))
                # build id-lists (untimed) for decode_batch
                encoded = tok.encode_batch(batch_texts)
                id_lists = [_to_id_list(e) for e in encoded]
                total_tokens = sum(len(ids) for ids in id_lists)
                dec_timing = time_one(lambda ids=id_lists: tok.decode_batch(ids))

                key = f"{bucket}|{batch_size}"
                enc_timing["batch_size"] = batch_size
                enc_timing["bucket"] = bucket
                enc_timing["total_tokens"] = total_tokens
                dec_timing["batch_size"] = batch_size
                dec_timing["bucket"] = bucket
                dec_timing["total_tokens"] = total_tokens
                model_timings["batch_encode"][key] = enc_timing
                model_timings["batch_decode"][key] = dec_timing
                manifest_rows.append({
                    "kind": "batch",
                    "model": model,
                    "bucket": bucket,
                    "batch_size": batch_size,
                    "sha1s": batch_shas,
                    "total_tokens": total_tokens,
                })
                log(
                    f"  batch bucket={bucket} batch_size={batch_size}: "
                    f"total_tokens={total_tokens} "
                    f"encode_med={enc_timing['median_ms']:.3f}ms "
                    f"decode_med={dec_timing['median_ms']:.3f}ms"
                )

        timings[model] = model_timings

    with INPUTS_BATCH_PATH.open("w", encoding="utf-8") as fh:
        for row in manifest_rows:
            fh.write(json.dumps(row) + "\n")
    TIMINGS_PATH.write_text(json.dumps(timings, indent=2), encoding="utf-8")

    log(f"\nWrote {INPUTS_BATCH_PATH} ({len(manifest_rows)} rows)")
    log(f"Wrote {TIMINGS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
